//! Parquet-based seed-data loaders for the showcase pipeline.
//!
//! These functions were extracted verbatim from
//! `helm-operator-control/src/pipeline.rs` as part of RFL-154 T5b.
//! They live here because `seed-gen` is the seed-IO layer: it both *writes*
//! the Parquet files (via `main.rs`) and now *reads* them back for pipeline
//! seeding.
//!
//! # Mounting-app usage
//!
//! The mounting app (not present in this workspace — see DONE_WITH_CONCERNS
//! note in the T5b report) should depend on `helm-module-contracts` and wrap
//! these functions (or equivalent logic) in a struct that implements
//! [`helm_module_contracts::showcase_pipeline::ShowcaseSeedSource`].
//!
//! # Known schema mismatch
//!
//! The Parquet files generated by `seed-gen/src/main.rs` use column names
//! `event_type` and `page_section` (singular). The loaders below read
//! `event_types` and `page_sections` (plural) — an existing inconsistency
//! inherited from the original `application-server` pipeline. A mounting app
//! implementing `ShowcaseSeedSource` should reconcile this against the actual
//! parquet schema before shipping.

// The functions in this module are intentionally unused inside the seed-gen
// binary itself; they exist for a mounting app to pick up (see module doc).
#![allow(dead_code)]

use std::path::Path;

use helm_module_contracts::showcase_pipeline::ShowcasePipelineInput;
use polars::prelude::*;

/// Load behavioral events from seed Parquet for a specific prospect.
/// Returns the events as a JSON string suitable for score-inbound-fit input.
pub fn load_prospect_events_from_seed(
    seed_dir: &Path,
    prospect_id: &str,
) -> Result<String, String> {
    let path = seed_dir.join("behavior_events.parquet");
    let parquet_path = path
        .to_str()
        .ok_or_else(|| format!("invalid parquet path: {}", path.display()))?;
    let df = LazyFrame::scan_parquet(PlPath::new(parquet_path), Default::default())
        .map_err(|e| format!("failed to read parquet: {e}"))?
        .filter(col("prospect_id").eq(lit(prospect_id)))
        .collect()
        .map_err(|e| format!("failed to filter prospect: {e}"))?;

    let mut events = Vec::new();
    let rows = df.height();
    for i in 0..rows {
        let visitor_id = df
            .column("prospect_id")
            .map_err(|e| e.to_string())?
            .str()
            .map_err(|e| e.to_string())?
            .get(i)
            .unwrap_or("");
        let timestamp = df
            .column("timestamp")
            .map_err(|e| e.to_string())?
            .i64()
            .map_err(|e| e.to_string())?
            .get(i)
            .unwrap_or(0);
        let event_type = df
            .column("event_types")
            .map_err(|e| e.to_string())?
            .str()
            .map_err(|e| e.to_string())?
            .get(i)
            .unwrap_or("");
        let page = df
            .column("page_sections")
            .map_err(|e| e.to_string())?
            .str()
            .map_err(|e| e.to_string())?
            .get(i)
            .unwrap_or("");

        events.push(serde_json::json!({
            "visitor_id": visitor_id,
            "timestamp": timestamp,
            "event_type": event_type,
            "page": page,
        }));
    }

    serde_json::to_string(&events).map_err(|e| format!("json serialization failed: {e}"))
}

/// Load account context from seed Parquet for a specific prospect.
pub fn load_prospect_context_from_seed(
    seed_dir: &Path,
    prospect_id: &str,
) -> Result<ShowcasePipelineInput, String> {
    let path = seed_dir.join("account_context.parquet");
    let parquet_path = path
        .to_str()
        .ok_or_else(|| format!("invalid parquet path: {}", path.display()))?;
    let df = LazyFrame::scan_parquet(PlPath::new(parquet_path), Default::default())
        .map_err(|e| format!("failed to read account_context parquet: {e}"))?
        .filter(col("prospect_id").eq(lit(prospect_id)))
        .collect()
        .map_err(|e| format!("failed to filter prospect: {e}"))?;

    if df.height() == 0 {
        return Err(format!(
            "prospect '{prospect_id}' not found in account_context"
        ));
    }

    let name = df
        .column("company_name")
        .ok()
        .and_then(|c| c.str().ok())
        .and_then(|s| s.get(0))
        .unwrap_or(prospect_id)
        .to_string();

    let industry = df
        .column("industry")
        .ok()
        .and_then(|c| c.str().ok())
        .and_then(|s| s.get(0))
        .map(ToString::to_string);

    let events_json = load_prospect_events_from_seed(seed_dir, prospect_id)?;

    Ok(ShowcasePipelineInput {
        prospect_name: name,
        visitor_id: prospect_id.to_string(),
        usage_events_json: events_json,
        inbound_summary: format!("Inbound inquiry from {prospect_id} via website demo request"),
        meeting_count: 1,
        window_start: "2026-04-21".into(),
        window_end: "2026-04-25".into(),
        calendar_slots_json: None,
        industry,
        website: None,
        contact_name: None,
        contact_title: None,
        contact_email: None,
    })
}
