Feature: Monitor brand signal

  Intent:
    Outcome: ingest external brand mentions, cluster them into narratives, and keep brand-state current without auto-publishing

  Scenario: Governed brand-state update from a monitoring cycle
    Given a BrandWatch exists for a party with configured sources
    And external signal ports have new raw items since the last cycle
    When the monitoring truth activates
    Then normalized mentions shall be proposed with source attribution
    And mentions shall be clustered into narrative clusters with reproducible embeddings
    And each cluster shall carry calibrated sentiment and salience
    And the brand-state projection for the party shall be refreshed
    But no outbound response shall be generated by this truth

  Scenario: High-severity incident requires human promotion
    Given a narrative cluster crosses the configured risk threshold
    When the risk agent proposes a SignalIncident at severity high
    Then the incident shall enter the approvals queue
    And the brand-state projection shall show the incident as pending
    But the incident shall not be promoted to a fact without human approval

  Scenario: Weak signal quality must not inflate confidence
    Given fewer than the minimum attributable sources for a cluster
    When sentiment and salience are scored
    Then the cluster shall be marked low-confidence
    And the cluster shall not contribute to share-of-voice aggregates
