fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .compile_protos(
            &[
                "../../proto/prio/common/v1/common.proto",
                "../../proto/prio/identity/v1/identity.proto",
                "../../proto/prio/parties/v1/parties.proto",
                "../../proto/prio/opportunities/v1/opportunities.proto",
                "../../proto/prio/conversations/v1/conversations.proto",
                "../../proto/prio/documents/v1/documents.proto",
                "../../proto/prio/workflow/v1/workflow.proto",
                "../../proto/prio/facts/v1/facts.proto",
                "../../proto/prio/metadata/v1/metadata.proto",
                "../../proto/prio/modules/v1/modules.proto",
                "../../proto/prio/truths/v1/truths.proto",
            ],
            &["../../proto"],
        )?;
    Ok(())
}
